language: python

python:
  - "2.7"
  - "3.2"
  - "3.3"

env:
  - DJANGO=1.6
  - DJANGO=1.5.5
  - DJANGO=1.4.10
  - DJANGO=1.3.7

install:
  - pip install -q -r requirements.txt --use-mirrors
  - pip install -q -I django==$DJANGO --use-mirrors
  - python setup.py -q install

matrix:
    exclude:
        - python: "3.2"
          env: DJANGO=1.3.7
        - python: "3.2"
          env: DJANGO=1.4.10
        - python: "3.3"
          env: DJANGO=1.3.7
        - python: "3.3"
          env: DJANGO=1.4.10

script: python setup.py test

after_success: coveralls --data_file coverage.xml
