language: python

python:
  - "2.7"
  - "3.2"
  - "3.3"

env:
  - DJANGO=1.6.1
  - DJANGO=1.5.5
  - DJANGO=1.4.10
  - DJANGO=1.3.7

install:
  - pip install -q -r requirements.txt --use-mirrors
  - pip install -q -I django==$DJANGO --use-mirrors
  - pip install python-coveralls --use-mirrors
  - python setup.py -q install

matrix:
    exclude:
        - python: "3.2"
          env: DJANGO=1.3.7
        - python: "3.2"
          env: DJANGO=1.4.10
        - python: "3.3"
          env: DJANGO=1.3.7
        - python: "3.3"
          env: DJANGO=1.4.10

script: py.test tests/ --cov admin_honeypot --cov-report term-missing

after_success: coveralls
